import { SupabaseClient } from "@supabase/supabase-js";
import { supabaseAdmin } from "src/lib/supabaseAdmin";

type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
type TriviaQuestionStatus = "draft" | "published" | "archived";
type TriviaQuestionType = "free_response" | "multiple_choice" | "true_false" | "ordering";
type TriviaDifficulty = "easy" | "medium" | "hard";
type TriviaCueSourceType = "inventory_track" | "uploaded_clip";
type TriviaAssetRole = "clue_primary" | "clue_secondary" | "answer_visual" | "explanation_media";
type TriviaAssetType = "image" | "audio" | "video";
type TriviaDeckStatus = "draft" | "ready" | "archived";
type TriviaDeckBuildMode = "manual" | "hybrid" | "rule";

export type TriviaDatabase = {
  public: {
    Tables: {
      events: {
        Row: {
          id: number;
          date: string;
          title: string;
          time: string | null;
          location: string | null;
        };
        Insert: {
          id?: number;
          date: string;
          title: string;
          time?: string | null;
          location?: string | null;
        };
        Update: {
          id?: number;
          date?: string;
          title?: string;
          time?: string | null;
          location?: string | null;
        };
        Relationships: [];
      };
      trivia_questions: {
        Row: {
          id: number;
          question_code: string;
          status: TriviaQuestionStatus;
          question_type: TriviaQuestionType;
          prompt_text: string;
          answer_key: string;
          accepted_answers: Json;
          answer_payload: Json;
          options_payload: Json;
          reveal_payload: Json;
          display_element_type: string;
          explanation_text: string | null;
          default_category: string;
          default_difficulty: TriviaDifficulty;
          source_note: string | null;
          is_tiebreaker_eligible: boolean;
          cue_source_type: TriviaCueSourceType | null;
          cue_source_payload: Json;
          primary_cue_start_seconds: number | null;
          primary_cue_end_seconds: number | null;
          primary_cue_instruction: string | null;
          cue_notes_text: string | null;
          cue_payload: Json;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          published_at: string | null;
          archived_at: string | null;
        };
        Insert: {
          id?: number;
          question_code: string;
          status?: TriviaQuestionStatus;
          question_type?: TriviaQuestionType;
          prompt_text: string;
          answer_key?: string;
          accepted_answers?: Json;
          answer_payload?: Json;
          options_payload?: Json;
          reveal_payload?: Json;
          display_element_type?: string;
          explanation_text?: string | null;
          default_category?: string;
          default_difficulty?: TriviaDifficulty;
          source_note?: string | null;
          is_tiebreaker_eligible?: boolean;
          cue_source_type?: TriviaCueSourceType | null;
          cue_source_payload?: Json;
          primary_cue_start_seconds?: number | null;
          primary_cue_end_seconds?: number | null;
          primary_cue_instruction?: string | null;
          cue_notes_text?: string | null;
          cue_payload?: Json;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          archived_at?: string | null;
        };
        Update: {
          id?: number;
          question_code?: string;
          status?: TriviaQuestionStatus;
          question_type?: TriviaQuestionType;
          prompt_text?: string;
          answer_key?: string;
          accepted_answers?: Json;
          answer_payload?: Json;
          options_payload?: Json;
          reveal_payload?: Json;
          display_element_type?: string;
          explanation_text?: string | null;
          default_category?: string;
          default_difficulty?: TriviaDifficulty;
          source_note?: string | null;
          is_tiebreaker_eligible?: boolean;
          cue_source_type?: TriviaCueSourceType | null;
          cue_source_payload?: Json;
          primary_cue_start_seconds?: number | null;
          primary_cue_end_seconds?: number | null;
          primary_cue_instruction?: string | null;
          cue_notes_text?: string | null;
          cue_payload?: Json;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      trivia_question_facets: {
        Row: {
          question_id: number;
          era: string | null;
          genre: string | null;
          decade: string | null;
          region: string | null;
          language: string | null;
          has_media: boolean;
          has_required_cue: boolean;
          difficulty: TriviaDifficulty;
          category: string;
        };
        Insert: {
          question_id: number;
          era?: string | null;
          genre?: string | null;
          decade?: string | null;
          region?: string | null;
          language?: string | null;
          has_media?: boolean;
          has_required_cue?: boolean;
          difficulty?: TriviaDifficulty;
          category?: string;
        };
        Update: {
          question_id?: number;
          era?: string | null;
          genre?: string | null;
          decade?: string | null;
          region?: string | null;
          language?: string | null;
          has_media?: boolean;
          has_required_cue?: boolean;
          difficulty?: TriviaDifficulty;
          category?: string;
        };
        Relationships: [];
      };
      trivia_question_tags: {
        Row: {
          id: number;
          question_id: number;
          tag: string;
          created_at: string;
        };
        Insert: {
          id?: number;
          question_id: number;
          tag: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          question_id?: number;
          tag?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      trivia_question_assets: {
        Row: {
          id: number;
          question_id: number;
          asset_role: TriviaAssetRole;
          asset_type: TriviaAssetType;
          bucket: string;
          object_path: string;
          mime_type: string | null;
          width: number | null;
          height: number | null;
          duration_seconds: number | null;
          sort_order: number;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          question_id: number;
          asset_role?: TriviaAssetRole;
          asset_type?: TriviaAssetType;
          bucket?: string;
          object_path: string;
          mime_type?: string | null;
          width?: number | null;
          height?: number | null;
          duration_seconds?: number | null;
          sort_order?: number;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          question_id?: number;
          asset_role?: TriviaAssetRole;
          asset_type?: TriviaAssetType;
          bucket?: string;
          object_path?: string;
          mime_type?: string | null;
          width?: number | null;
          height?: number | null;
          duration_seconds?: number | null;
          sort_order?: number;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      trivia_decks: {
        Row: {
          id: number;
          deck_code: string;
          title: string;
          status: TriviaDeckStatus;
          event_id: number | null;
          playlist_id: number | null;
          build_mode: TriviaDeckBuildMode;
          rules_payload: Json;
          cooldown_days: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          locked_at: string | null;
        };
        Insert: {
          id?: number;
          deck_code: string;
          title: string;
          status?: TriviaDeckStatus;
          event_id?: number | null;
          playlist_id?: number | null;
          build_mode?: TriviaDeckBuildMode;
          rules_payload?: Json;
          cooldown_days?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          locked_at?: string | null;
        };
        Update: {
          id?: number;
          deck_code?: string;
          title?: string;
          status?: TriviaDeckStatus;
          event_id?: number | null;
          playlist_id?: number | null;
          build_mode?: TriviaDeckBuildMode;
          rules_payload?: Json;
          cooldown_days?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          locked_at?: string | null;
        };
        Relationships: [];
      };
      trivia_deck_items: {
        Row: {
          id: number;
          deck_id: number;
          item_index: number;
          round_number: number;
          is_tiebreaker: boolean;
          question_id: number | null;
          snapshot_payload: Json;
          locked: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          deck_id: number;
          item_index: number;
          round_number?: number;
          is_tiebreaker?: boolean;
          question_id?: number | null;
          snapshot_payload?: Json;
          locked?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          deck_id?: number;
          item_index?: number;
          round_number?: number;
          is_tiebreaker?: boolean;
          question_id?: number | null;
          snapshot_payload?: Json;
          locked?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      trivia_sessions: {
        Row: {
          id: number;
          event_id: number | null;
          playlist_id: number | null;
          deck_id: number | null;
          session_code: string;
          title: string;
          round_count: number;
          questions_per_round: number;
          tie_breaker_count: number;
          score_mode: string;
          question_categories: string[];
          difficulty_easy_target: number;
          difficulty_medium_target: number;
          difficulty_hard_target: number;
          remove_resleeve_seconds: number;
          find_record_seconds: number;
          cue_seconds: number;
          host_buffer_seconds: number;
          target_gap_seconds: number;
          current_round: number;
          current_call_index: number;
          countdown_started_at: string | null;
          paused_remaining_seconds: number | null;
          paused_at: string | null;
          show_title: boolean;
          show_rounds: boolean;
          show_question_counter: boolean;
          show_leaderboard: boolean;
          show_cue_hints: boolean;
          max_teams: number | null;
          slips_batch_size: number | null;
          status: string;
          created_at: string;
          started_at: string | null;
          ended_at: string | null;
        };
        Insert: {
          id?: number;
          event_id?: number | null;
          playlist_id?: number | null;
          deck_id?: number | null;
          session_code: string;
          title: string;
          round_count?: number;
          questions_per_round?: number;
          tie_breaker_count?: number;
          score_mode?: string;
          question_categories?: string[];
          difficulty_easy_target?: number;
          difficulty_medium_target?: number;
          difficulty_hard_target?: number;
          remove_resleeve_seconds?: number;
          find_record_seconds?: number;
          cue_seconds?: number;
          host_buffer_seconds?: number;
          target_gap_seconds?: number;
          current_round?: number;
          current_call_index?: number;
          countdown_started_at?: string | null;
          paused_remaining_seconds?: number | null;
          paused_at?: string | null;
          show_title?: boolean;
          show_rounds?: boolean;
          show_question_counter?: boolean;
          show_leaderboard?: boolean;
          show_cue_hints?: boolean;
          max_teams?: number | null;
          slips_batch_size?: number | null;
          status?: string;
          created_at?: string;
          started_at?: string | null;
          ended_at?: string | null;
        };
        Update: {
          id?: number;
          event_id?: number | null;
          playlist_id?: number | null;
          deck_id?: number | null;
          session_code?: string;
          title?: string;
          round_count?: number;
          questions_per_round?: number;
          tie_breaker_count?: number;
          score_mode?: string;
          question_categories?: string[];
          difficulty_easy_target?: number;
          difficulty_medium_target?: number;
          difficulty_hard_target?: number;
          remove_resleeve_seconds?: number;
          find_record_seconds?: number;
          cue_seconds?: number;
          host_buffer_seconds?: number;
          target_gap_seconds?: number;
          current_round?: number;
          current_call_index?: number;
          countdown_started_at?: string | null;
          paused_remaining_seconds?: number | null;
          paused_at?: string | null;
          show_title?: boolean;
          show_rounds?: boolean;
          show_question_counter?: boolean;
          show_leaderboard?: boolean;
          show_cue_hints?: boolean;
          max_teams?: number | null;
          slips_batch_size?: number | null;
          status?: string;
          created_at?: string;
          started_at?: string | null;
          ended_at?: string | null;
        };
        Relationships: [];
      };
      trivia_session_teams: {
        Row: {
          id: number;
          session_id: number;
          team_name: string;
          table_label: string | null;
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          session_id: number;
          team_name: string;
          table_label?: string | null;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          session_id?: number;
          team_name?: string;
          table_label?: string | null;
          active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      trivia_session_calls: {
        Row: {
          id: number;
          session_id: number;
          round_number: number;
          call_index: number;
          playlist_track_key: string | null;
          question_id: number | null;
          question_type: TriviaQuestionType;
          is_tiebreaker: boolean;
          category: string;
          difficulty: string;
          question_text: string;
          answer_key: string;
          accepted_answers: Json;
          options_payload: Json;
          answer_payload: Json;
          explanation_text: string | null;
          reveal_payload: Json;
          source_note: string | null;
          cue_source_type: TriviaCueSourceType | null;
          cue_source_payload: Json;
          primary_cue_start_seconds: number | null;
          primary_cue_end_seconds: number | null;
          primary_cue_instruction: string | null;
          cue_notes_text: string | null;
          cue_payload: Json;
          prep_status: string;
          display_element_type: string;
          display_image_override_url: string | null;
          auto_cover_art_url: string | null;
          auto_vinyl_label_url: string | null;
          source_artist: string | null;
          source_title: string | null;
          source_album: string | null;
          source_side: string | null;
          source_position: string | null;
          metadata_locked: boolean;
          metadata_synced_at: string | null;
          base_points: number;
          bonus_points: number;
          status: string;
          asked_at: string | null;
          answer_revealed_at: string | null;
          scored_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          session_id: number;
          round_number: number;
          call_index: number;
          playlist_track_key?: string | null;
          question_id?: number | null;
          question_type?: TriviaQuestionType;
          is_tiebreaker?: boolean;
          category: string;
          difficulty: string;
          question_text: string;
          answer_key: string;
          accepted_answers?: Json;
          options_payload?: Json;
          answer_payload?: Json;
          explanation_text?: string | null;
          reveal_payload?: Json;
          source_note?: string | null;
          cue_source_type?: TriviaCueSourceType | null;
          cue_source_payload?: Json;
          primary_cue_start_seconds?: number | null;
          primary_cue_end_seconds?: number | null;
          primary_cue_instruction?: string | null;
          cue_notes_text?: string | null;
          cue_payload?: Json;
          prep_status?: string;
          display_element_type?: string;
          display_image_override_url?: string | null;
          auto_cover_art_url?: string | null;
          auto_vinyl_label_url?: string | null;
          source_artist?: string | null;
          source_title?: string | null;
          source_album?: string | null;
          source_side?: string | null;
          source_position?: string | null;
          metadata_locked?: boolean;
          metadata_synced_at?: string | null;
          base_points?: number;
          bonus_points?: number;
          status?: string;
          asked_at?: string | null;
          answer_revealed_at?: string | null;
          scored_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          session_id?: number;
          round_number?: number;
          call_index?: number;
          playlist_track_key?: string | null;
          question_id?: number | null;
          question_type?: TriviaQuestionType;
          is_tiebreaker?: boolean;
          category?: string;
          difficulty?: string;
          question_text?: string;
          answer_key?: string;
          accepted_answers?: Json;
          options_payload?: Json;
          answer_payload?: Json;
          explanation_text?: string | null;
          reveal_payload?: Json;
          source_note?: string | null;
          cue_source_type?: TriviaCueSourceType | null;
          cue_source_payload?: Json;
          primary_cue_start_seconds?: number | null;
          primary_cue_end_seconds?: number | null;
          primary_cue_instruction?: string | null;
          cue_notes_text?: string | null;
          cue_payload?: Json;
          prep_status?: string;
          display_element_type?: string;
          display_image_override_url?: string | null;
          auto_cover_art_url?: string | null;
          auto_vinyl_label_url?: string | null;
          source_artist?: string | null;
          source_title?: string | null;
          source_album?: string | null;
          source_side?: string | null;
          source_position?: string | null;
          metadata_locked?: boolean;
          metadata_synced_at?: string | null;
          base_points?: number;
          bonus_points?: number;
          status?: string;
          asked_at?: string | null;
          answer_revealed_at?: string | null;
          scored_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      trivia_team_scores: {
        Row: {
          id: number;
          session_id: number;
          team_id: number;
          call_id: number;
          awarded_points: number;
          correct: boolean;
          scored_by: string | null;
          notes: string | null;
          scored_at: string;
          created_at: string;
        };
        Insert: {
          id?: number;
          session_id: number;
          team_id: number;
          call_id: number;
          awarded_points: number;
          correct: boolean;
          scored_by?: string | null;
          notes?: string | null;
          scored_at?: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          session_id?: number;
          team_id?: number;
          call_id?: number;
          awarded_points?: number;
          correct?: boolean;
          scored_by?: string | null;
          notes?: string | null;
          scored_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      trivia_session_events: {
        Row: {
          id: number;
          session_id: number;
          event_type: string;
          payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          session_id: number;
          event_type: string;
          payload?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          session_id?: number;
          event_type?: string;
          payload?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type TriviaDbClient = SupabaseClient<TriviaDatabase>;

export function getTriviaDb(): TriviaDbClient {
  return supabaseAdmin as unknown as TriviaDbClient;
}
