export interface CollectionTrackRow {
  key: string;
  inventoryId: number;
  releaseTrackId: number | null;
  recordingId: number | null;
  albumArtist: string;
  albumTitle: string;
  trackArtist: string;
  trackTitle: string;
  position: string;
  side: string | null;
  durationSeconds: number | null;
  durationLabel: string;
  albumMediaType: string;
  trackFormatFacets: string[];
  format?: string | null;
  country?: string | null;
  location?: string | null;
  status?: string | null;
  barcode?: string | null;
  catalogNumber?: string | null;
  label?: string | null;
  owner?: string | null;
  personalNotes?: string | null;
  releaseNotes?: string | null;
  masterNotes?: string | null;
  mediaCondition?: string | null;
  sleeveCondition?: string | null;
  packageSleeveCondition?: string | null;
  packaging?: string | null;
  studio?: string | null;
  sound?: string | null;
  vinylWeight?: string | null;
  rpm?: string | null;
  sparsCode?: string | null;
  boxSet?: string | null;
  purchaseStore?: string | null;
  notes?: string | null;
  composer?: string | null;
  conductor?: string | null;
  chorus?: string | null;
  composition?: string | null;
  orchestra?: string | null;
  yearInt?: number | null;
  decade?: number | null;
  myRating?: number | null;
  playCount?: number | null;
  discs?: number | null;
  sides?: number | null;
  indexNumber?: number | null;
  purchasePrice?: number | null;
  currentValue?: number | null;
  dateAdded?: string | null;
  purchaseDate?: string | null;
  lastPlayedAt?: string | null;
  lastCleanedDate?: string | null;
  originalReleaseDate?: string | null;
  recordingDate?: string | null;
  forSale?: boolean;
  isLive?: boolean;
  is1001?: boolean;
  customTags?: string[];
  discogsGenres?: string[];
  spotifyGenres?: string[];
  labels?: string[];
  signedBy?: string[];
  songwriters?: string[];
  producers?: string[];
  engineers?: string[];
  musicians?: string[];
}
