export interface SharedIconPreset {
  icon: string;
  keywords: string[];
}

export const SHARED_ICON_PRESETS: SharedIconPreset[] = [
  { icon: '📦', keywords: ['crate', 'box', 'collection'] },
  { icon: '🎱', keywords: ['pool'] },
  { icon: '❓', keywords: ['question', 'quiz'] },
  { icon: '🏆', keywords: ['tournament', 'winner'] },
  { icon: '🎮', keywords: ['gaming', 'other'] },
  { icon: '🎲', keywords: ['dice', 'board', 'random'] },
  { icon: '🧩', keywords: ['puzzle', 'piece'] },
  { icon: '🎯', keywords: ['target', 'focus'] },
  { icon: '🃏', keywords: ['cards', 'joker'] },
  { icon: '🎵', keywords: ['music', 'track', 'playlist'] },
  { icon: '🎧', keywords: ['headphones', 'listen', 'dj'] },
  { icon: '🎤', keywords: ['mic', 'vocal', 'karaoke'] },
  { icon: '🎸', keywords: ['guitar', 'rock', 'band'] },
  { icon: '🎹', keywords: ['keys', 'piano', 'synth'] },
  { icon: '🎷', keywords: ['sax', 'jazz'] },
  { icon: '🎺', keywords: ['horn', 'brass'] },
  { icon: '🥁', keywords: ['drums', 'rhythm', 'beat'] },
  { icon: '💿', keywords: ['cd', 'disc', 'digital'] },
  { icon: '📀', keywords: ['dvd', 'optical', 'disc'] },
  { icon: '🔥', keywords: ['hot', 'favorite', 'energy'] },
  { icon: '⭐', keywords: ['star', 'favorite', 'top'] },
  { icon: '💎', keywords: ['diamond', 'premium', 'gem'] },
  { icon: '🚀', keywords: ['launch', 'boost', 'new'] },
  { icon: '⚡', keywords: ['electric', 'fast', 'power'] },
  { icon: '🌟', keywords: ['glow', 'featured'] },
  { icon: '🪩', keywords: ['dance', 'disco', 'party'] },
  { icon: '🎪', keywords: ['show', 'event', 'circus'] },
  { icon: '🕺', keywords: ['dance', 'party', 'club'] },
  { icon: '💃', keywords: ['dance', 'party', 'club'] },
  { icon: '🎉', keywords: ['party', 'celebrate'] },
  { icon: '🎊', keywords: ['celebrate', 'event'] },
  { icon: '🥳', keywords: ['party', 'fun'] },
  { icon: '🍾', keywords: ['toast', 'celebrate'] },
  { icon: '🪄', keywords: ['magic', 'special'] },
  { icon: '🎬', keywords: ['movie', 'scene', 'show'] },
  { icon: '❤️', keywords: ['love', 'heart', 'favorite'] },
  { icon: '💙', keywords: ['blue', 'heart'] },
  { icon: '💚', keywords: ['green', 'heart'] },
  { icon: '💛', keywords: ['yellow', 'heart'] },
  { icon: '🧡', keywords: ['orange', 'heart'] },
  { icon: '💜', keywords: ['purple', 'heart'] },
  { icon: '🖤', keywords: ['black', 'heart'] },
  { icon: '🤍', keywords: ['white', 'heart'] },
  { icon: '📌', keywords: ['pin', 'saved'] },
  { icon: '✅', keywords: ['done', 'check'] },
  { icon: '🆕', keywords: ['new', 'fresh'] },
  { icon: '🔒', keywords: ['private', 'lock'] },
  { icon: '🔓', keywords: ['open', 'unlock'] },
  { icon: '🧠', keywords: ['brain', 'smart'] },
  { icon: '🛸', keywords: ['space', 'weird'] },
  { icon: '👑', keywords: ['king', 'queen', 'top'] },
  { icon: '🐺', keywords: ['wolf', 'animal'] },
  { icon: '🦅', keywords: ['eagle', 'animal'] },
  { icon: '🐍', keywords: ['snake', 'animal'] },
  { icon: '🦁', keywords: ['lion', 'animal'] },
  { icon: '🐯', keywords: ['tiger', 'animal'] },
  { icon: '🦈', keywords: ['shark', 'animal'] },
  { icon: '🦄', keywords: ['unicorn', 'fantasy'] },
  { icon: '🐉', keywords: ['dragon', 'fantasy'] },
];

export const SHARED_COLOR_PRESETS = [
  '#3578b3',
  '#ef4444',
  '#f59e0b',
  '#10b981',
  '#8b5cf6',
  '#ec4899',
  '#06b6d4',
  '#64748b',
  '#111827',
];
