-- ─── VINYL COLORS ────────────────────────────────────────────────────────────
-- Replace all color entries with the canonical urpressing.com list.
-- Safe to re-run (DELETE + INSERT is idempotent).

DELETE FROM format_abbreviations WHERE category = 'color';

INSERT INTO format_abbreviations (category, abbreviation, name) VALUES
-- Opaque
('color', 'O-1',   'Black'),
('color', 'O-2',   'White'),
('color', 'O-3',   'Orange'),
('color', 'O-4',   'Red'),
('color', 'O-5',   'Turquoise'),
('color', 'O-6',   'Yellow'),
('color', 'O-7',   'Forest Green'),
('color', 'O-8',   'Green'),
('color', 'O-9',   'Emerald'),
('color', 'O-10',  'Olive Drab Green'),
('color', 'O-11',  'Blue'),
('color', 'O-12',  'Purple'),
('color', 'O-13',  'Pink'),
('color', 'O-14',  'Brown'),
('color', 'O-103', 'Inferno'),
('color', 'O-104', 'Mac n Cheese'),
('color', 'O-105', 'Forsythia'),
('color', 'O-107', 'Neptune'),
('color', 'O-108', 'Live Through This'),
('color', 'O-109', 'Dream Pop'),
('color', 'O-110', 'Chocolate'),
-- Translucent
('color', 'T-1',   'Yellow'),
('color', 'T-2',   'Blue'),
('color', 'T-3',   'Orange'),
('color', 'T-4',   'Red'),
('color', 'T-5',   'Green'),
('color', 'T-6',   'Pink'),
('color', 'T-7',   'Magenta'),
('color', 'T-9',   'Swamp Green'),
('color', 'T-10',  'Gold'),
('color', 'T-11',  'Sea Glass'),
('color', 'T-12',  'Clear'),
('color', 'T-13',  'Frost'),
('color', 'T-14',  'Ultra Clear'),
('color', 'T-15',  'Tan'),
('color', 'T-17',  'Black Ice'),
('color', 'T-201', 'Candy Apple Red'),
('color', 'T-202', 'Juice'),
('color', 'T-203', 'Mellow Gold'),
('color', 'T-204', 'Lemon Drop'),
('color', 'T-206', 'Emerald'),
('color', 'T-208', 'Blue Hour'),
('color', 'T-210', 'Comic Sands'),
('color', 'T-211', 'Window Pane'),
-- Metallic
('color', 'M-1',   'Pure Gold'),
('color', 'M-2',   'Silver'),
('color', 'M-111', 'Alchemy'),
('color', 'M-112', 'Pewter'),
-- Neon
('color', 'N-1',   'Red'),
('color', 'N-2',   'Purple'),
('color', 'N-3',   'Yellow'),
('color', 'N-4',   'Pink'),
('color', 'N-5',   'Green'),
('color', 'N-6',   'Orange'),
-- Pastel
('color', 'P-1',   'Baby Blue'),
('color', 'P-2',   'Yellow'),
('color', 'P-3',   'Orange'),
('color', 'P-4',   'Custard'),
('color', 'P-5',   'Pink'),
('color', 'P-6',   'Light Violet'),
('color', 'P-7',   'Violet'),
('color', 'P-8',   'Green'),
-- Custom Mix
('color', '301',   'Storm'),
('color', '302',   'Crystal Ball'),
('color', '304',   'Sangria'),
('color', '305',   'Cherry Glaze'),
('color', '306',   'Peach'),
('color', '307',   'Motown Suite Orange'),
('color', '308',   'Radiation'),
('color', '309',   'Séance'),
('color', '310',   'Amber Fossil'),
('color', '311',   'Tabby Cat'),
('color', '312',   'Lemonade'),
('color', '314',   'Cockatiel'),
('color', '315',   'Slime'),
('color', '316',   'Malachite'),
('color', '317',   'Swamp'),
('color', '318',   'Glacier'),
('color', '319',   'Mermaid'),
('color', '320',   'Motown Suite Teal'),
('color', '321',   'Sea Foam'),
('color', '322',   'Atlantis'),
('color', '323',   'Good Jeans'),
('color', '324',   'Hatful of Hollow'),
('color', '325',   'Helium'),
('color', '326',   'Nevermind'),
('color', '327',   'Purple Haze'),
('color', '328',   'Because the Night'),
('color', '329',   'Rose Quartz'),
('color', '330',   'Synthwave'),
('color', '331',   'Yoshimi'),
('color', '332',   'Vice City'),
('color', '333',   'Root Beer'),
('color', '334',   'Buttered Popcorn'),
('color', '335',   'Pangaea'),
('color', '336',   'Nashville Public Library Parking Garage'),
-- New Wave
('color', '401',   'Energy Dome'),
('color', '402',   'Psycho Killer'),
('color', '403',   'Rip It Up'),
('color', '404',   'Brass in Pocket'),
('color', '405',   'Bananarama'),
('color', '406',   'Dangerous Type'),
('color', '407',   'Radioactivity'),
('color', '408',   'Wild Planet'),
('color', '409',   'Everything''s Gone Green'),
('color', '410',   'Ocean Rain'),
('color', '411',   'Blue Monday'),
('color', '412',   'Are ''Friends'' Electric?'),
('color', '413',   'Atrocity Exhibition'),
('color', '414',   'Cosmic Thing'),
('color', '415',   'Head Over Heels'),
('color', '416',   'I Want Candy'),
('color', '417',   'The King of Rock ''n'' Roll'),
('color', '418',   'Missing Persons'),
-- 2-Color Split
('color', '501',   'Pink & Clear Split'),
-- Random Eco-Mix
('color', '601',   'Random Mix'),
-- Random Eco-Mix Split
('color', '701',   'Random Mix Split');


-- ─── PACKAGING ───────────────────────────────────────────────────────────────
-- Replace all packaging entries with a clean canonical list.

DELETE FROM format_abbreviations WHERE category = 'packaging';

INSERT INTO format_abbreviations (category, abbreviation, name) VALUES
-- Vinyl LP / EP
('packaging', 'GAT',  'Gatefold'),
('packaging', 'TRI',  'Tri-fold'),
('packaging', 'FLP',  'Flipback'),
('packaging', 'FLY',  'Flyout'),
('packaging', 'SOL',  'Solo Sleeve'),
('packaging', 'DIE',  'Die-cut'),
('packaging', 'EMB',  'Embossed'),
('packaging', 'GIM',  'Gimmick'),
('packaging', 'OBI',  'Obi'),
('packaging', 'POS',  'Poster'),
-- Vinyl Singles
('packaging', 'PIC',  'Picture Sleeve'),
('packaging', 'PLN',  'Plain Sleeve'),
-- CD
('packaging', 'JWL',  'Jewel Case'),
('packaging', 'SLM',  'Slimline'),
('packaging', 'DIG',  'Digipak'),
('packaging', 'SLP',  'Slipcase'),
('packaging', 'OCA',  'O-card'),
('packaging', 'PPR',  'Paper Sleeve'),
('packaging', 'CRD',  'Carded');
